import BlogNav from "@/components/blog/BlogNav";
import Hero from "@/components/blog/Hero";
import Infobox from "@/components/blog/Infobox";
import TableOfContents from "@/components/blog/TableOfContents";
import CodeBlock from "@/components/blog/CodeBlock";
import StackTable from "@/components/blog/StackTable";
import FusionLayers from "@/components/blog/FusionLayers";

import architecture from "@/assets/architecture-diagram.png";
import dashboard from "@/assets/photo_2026-04-26_12-58-15.jpg";
import realtimeMonitoring from "@/assets/photo_2026-04-26_12-58-14.jpg";
import extensionUi from "@/assets/extension-ui.jpg";
import codeCore from "@/assets/code-core-engine.jpg";
import codeFusion from "@/assets/code-fusion.jpg";
import codeUrl from "@/assets/code-url-intel.jpg";
import codeThreat from "@/assets/code-threat-id.jpg";
import dataset from "@/assets/dataset-preview.jpg";

const Index = () => {
  return (
    <div className="min-h-screen bg-gray-50">
      <BlogNav />

      <main className="container mx-auto py-8 max-w-4xl">
        <div className="bg-white rounded-xl shadow-lg p-8 mb-8">
          <Hero />
        </div>

        <article className="blog-prose relative bg-white rounded-xl shadow-lg p-8">
          <div className="section-card">
            <Infobox />
          </div>

          {/* Abstract */}
          <div className="section-card">
            <h2 className="text-2xl font-bold mb-4 text-primary">Abstract</h2>
          <p>
            <strong>TrustShield AI</strong> is a multi-layered, AI-driven phishing detection
            framework designed to identify and mitigate sophisticated email-based attacks
            in real time. Built on a three-tier architecture comprising a frontend dashboard,
            a Flask-based asynchronous backend, and a MongoDB persistence layer, the system
            fuses six independent intelligence signals — machine learning prediction, URL
            intelligence, rule heuristics, emotional analysis, behavioural anomalies and
            attachment inspection — into a single sub-second verdict. Verdicts are
            accompanied by natural-language explanations generated by a locally hosted
            large language model (LLM).
          </p>
          <p>
            The system continuously stores every analyzed email, along with its classification
            metadata, in a live <em>retraining corpus</em> that is later used to update the
            active model. This ensures that the detection engine adapts to new phishing
            techniques and evolving attack patterns over time. TrustShield AI integrates
            with email clients through a Chrome Manifest&nbsp;V3 browser extension and with
            security operations teams through a real-time SOC dashboard.
          </p>
          </div>

          <div className="section-card">
            <TableOfContents />
          </div>

          {/* 1. Overview */}
          <div className="section-card">
            <h2 id="sec-1" className="blog-h2">1. Overview</h2>
          <p>
            Phishing remains one of the most pervasive and damaging vectors in modern
            cybersecurity. Traditional rule-based spam filters rely on static keyword lists
            and sender blocklists, which attackers routinely defeat through paraphrasing,
            typosquatting, and personalised spear-phishing campaigns. TrustShield AI was
            designed to address this gap by combining classical machine learning, rule
            heuristics, and language-model reasoning in a single low-latency pipeline.
          </p>

            <div className="highlight-box">
              "TrustShield does not replace human judgement — it protects the human inside
              the loop, reducing cognitive load on the people most often targeted by
              phishing campaigns."
            </div>

          <p>
            The framework is intentionally lightweight. It runs on commodity hardware, uses
            an asynchronous Flask backend for non-blocking inference, and depends only on
            open-source libraries. Every architectural decision is biased toward
            <em> observability</em>, <em>explainability</em>, and <em>continuous learning</em>.
          </p>

          </div>

          {/* 2. Background */}
          <div className="section-card">
            <h2 id="sec-2" className="blog-h2">2. Background and motivation</h2>
          <p>
            Conventional email security deployments compute threat levels from static
            rule-sets that perform minimal processing on inbound mail. As a result, large
            volumes of malicious messages still reach end-users. Three structural problems
            motivated the design of TrustShield AI:
          </p>
          <ul>
            <li>
              <strong>Exposure window.</strong> When a phishing campaign slips past static
              filters, the user becomes the last line of defence — a position humans are
              consistently poor at occupying.
            </li>
            <li>
              <strong>Rigidity of hardcoded rules.</strong> Trigger-word filters cannot
              keep pace with adversarial paraphrasing or LLM-generated phishing content.
            </li>
            <li>
              <strong>Latency budget.</strong> Robust analysis must not delay mail delivery.
              Any practical solution has only a few hundred milliseconds per message.
            </li>
          </ul>
          <p>
            TrustShield's response is the <strong>TrustShield Orchestrator (TSO)</strong> —
            a horizontally cooperating set of intelligence modules rather than a monolithic
            classifier. The orchestrator coordinates analysis across three architectural
            tiers and six analytic layers, returning a unified verdict that is both
            quantitative (a trust score) and qualitative (a natural-language explanation).
          </p>
          </div>

          {/* 3. Architecture */}
          <div className="section-card">
            <h2 id="sec-3" className="blog-h2">3. System architecture</h2>

          <h3 className="blog-h3">3.1 Three-tier design</h3>
          <p>
            TrustShield AI is structured into three logical tiers. This separation allows
            each tier to scale, fail and be replaced independently of the others.
          </p>
          <table className="blog-table">
            <thead>
              <tr>
                <th>Tier</th>
                <th>Components</th>
                <th>Responsibility</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="font-semibold">Presentation</td>
                <td>SOC dashboard · Chrome extension</td>
                <td>Surfaces verdicts, alerts and live telemetry to the user.</td>
              </tr>
              <tr>
                <td className="font-semibold">Application</td>
                <td>Flask API · asyncio executor · Detection engine · LLM gateway</td>
                <td>Performs analysis, fusion scoring and explanation generation.</td>
              </tr>
              <tr>
                <td className="font-semibold">Data</td>
                <td>MongoDB · Model registry · Retrain corpus</td>
                <td>Persists scans, model artifacts and the living dataset.</td>
              </tr>
            </tbody>
          </table>

          <h3 className="blog-h3">3.2 Architectural diagram</h3>
          <figure className="blog-figure">
            <img src={architecture} alt="TrustShield AI complete system architecture diagram" loading="lazy" />
            <figcaption>
              <strong>Figure 1.</strong> End-to-end TrustShield AI architecture. Inbound
              email flows through the Flask asynchronous edge into six parallel analysis
              layers; verdicts are persisted to MongoDB and surfaced on the SOC dashboard.
            </figcaption>
          </figure>
          </div>

          {/* 4. Stack */}
          <div className="section-card">
            <h2 id="sec-4" className="blog-h2">4. Technology stack</h2>
          <p>
            The project is implemented entirely in open-source technologies. The table
            below enumerates each architectural layer, the technology used, and its
            purpose within the system.
          </p>
          <StackTable />
          <p className="text-sm text-muted-foreground italic">
            <strong>Table 1.</strong> Engineering stack of TrustShield AI.
          </p>
          </div>

          {/* 5. Detection engine */}
          <div className="section-card">
            <h2 id="sec-5" className="blog-h2">5. Detection engine</h2>
          <p>
            The detection engine is the analytic core of TrustShield AI. Each incoming
            email is normalised, vectorised and dispatched to a non-blocking executor that
            runs ML inference alongside five rule-driven intelligence modules. The layers
            do not wait on each other — the pipeline keeps moving even as the LLM
            generates a human-readable explanation in the background.
          </p>

          <h3 className="blog-h3">5.1 Aggressive fusion</h3>
          <p>
            TrustShield uses a strategy referred to internally as <em>aggressive fusion</em>.
            Every layer returns a numeric score in <span className="mono">[0, 1]</span>.
            A weighted base score is computed across all layers, then multiplied by a
            contextual <strong>risk multiplier</strong> when the message touches financial
            keywords, account-state language or high emotional intensity. A trust score
            below the critical threshold flips the verdict to
            <em> phishing · critical risk</em>.
          </p>

          <h3 className="blog-h3">5.2 Scoring layers</h3>
          <p>
            The six intelligence layers and their default fusion weights are as follows.
          </p>
          <FusionLayers />
          <p className="text-sm text-muted-foreground italic">
            <strong>Table 2.</strong> Default weights of the aggressive fusion algorithm.
            Weights are configurable per deployment.
          </p>

          <h3 className="blog-h3">5.3 Code reference</h3>
          <p>
            The following figures show the relevant source modules from the TrustShield
            backend. They illustrate the asynchronous orchestration, the fusion scoring
            arithmetic, and the URL intelligence heuristics.
          </p>

          <CodeBlock
            caption="detection/engine.py — analyze_text()"
            description="Figure 2. Non-blocking ML inference and parallel intelligence calls within the core engine."
            src={codeCore}
            alt="Python code: async analyze_text core engine"
          />

          <CodeBlock
            caption="detection/scoring.py — aggressive fusion"
            description="Figure 3. Weighted base score combined with a contextual risk multiplier for financial, threat and emotional escalation."
            src={codeFusion}
            alt="Python code: aggressive fusion scoring with risk multipliers"
          />

          <CodeBlock
            caption="detection/url_intelligence.py"
            description="Figure 4. URL signal counter — credential keywords, risky TLDs, shorteners and IP-encoded hosts."
            src={codeUrl}
            alt="Python code: URL intelligence signal counter"
          />

          <CodeBlock
            caption="detection/engine.py — verdict response"
            description="Figure 5. Final verdict construction including classification, risk_level, trust_score, attack_type and the LLM-generated explanation."
            src={codeThreat}
            alt="Python code: final verdict construction with LLM explanation"
          />
          </div>

          {/* 6. Dashboard */}
          <div className="section-card">
            <h2 id="sec-6" className="blog-h2">6. SOC dashboard</h2>
          <p>
            The Security Operations Centre (SOC) dashboard is a web-based interface that
            allows security analysts to monitor the live behaviour of TrustShield AI. It
            is implemented in HTML, CSS and Vanilla JavaScript, and consumes the same
            Flask API as the browser extension.
          </p>
          <figure className="blog-figure">
            <img src={dashboard} alt="TrustShield SOC dashboard" loading="lazy" />
            <figcaption>
              <strong>Figure 6.</strong> Screenshot of the TrustShield SOC dashboard
              showing the live activity feed, model information panel and risk-trend
              charts.
            </figcaption>
          </figure>

          <h4 className="blog-h4">Real-time Threat Monitoring Interface</h4>
          <figure className="blog-figure">
            <img src={realtimeMonitoring} alt="TrustShield AI real-time threat monitoring interface" loading="lazy" />
            <figcaption>
              <strong>Figure 6.1.</strong> Live threat monitoring interface displaying real-time phishing detection results,
              risk scores, and automated threat intelligence feeds from the TrustShield AI system.
            </figcaption>
          </figure>
          <p>The dashboard surfaces four primary views:</p>
          <ul>
            <li><strong>Live activity feed.</strong> Every scan and every verdict, streamed in real time.</li>
            <li><strong>Risk levels and trends.</strong> Hourly and daily phishing pressure, segmented per tenant.</li>
            <li><strong>Model information.</strong> Active model version, accuracy, calibration and drift indicators.</li>
            <li><strong>Alerts and notifications.</strong> High-risk verdicts, drift alarms and pipeline failures, wired to operations channels.</li>
          </ul>
          </div>

          {/* 7. Extension */}
          <div className="section-card">
            <h2 id="sec-7" className="blog-h2">7. Browser extension</h2>
          <p>
            The TrustShield browser extension is implemented as a Chrome
            <em> Manifest V3</em> extension. It reads the email body and embedded URLs the
            instant a message is opened inside Gmail or Outlook, posts the payload to the
            <span className="mono"> /analyze </span> endpoint over HTTPS, and renders the
            verdict inline within the email client.
          </p>
          <figure className="blog-figure md:float-right md:w-[380px] md:ml-6 md:mb-4">
            <img src={extensionUi} alt="Chrome extension showing phishing verdict inside Gmail" loading="lazy" />
            <figcaption>
              <strong>Figure 7.</strong> The TrustShield Chrome extension rendering an
              inline phishing verdict inside a Gmail message.
            </figcaption>
          </figure>
          <p>The extension performs four steps for each opened message:</p>
          <ol>
            <li>Reads the email content and extracts URLs from the active DOM.</li>
            <li>Sends the payload to the Flask <span className="mono">/analyze</span> endpoint with a rotating API key.</li>
            <li>Displays the risk score, classification and triggered rules to the user.</li>
            <li>Mirrors the verdict to the SOC dashboard via the same logging spine.</li>
          </ol>
          <div style={{ clear: "both" }} />
          </div>

          {/* 8. Living dataset */}
          <div className="section-card">
            <h2 id="sec-8" className="blog-h2">8. Living retraining dataset</h2>
          <p>
            A central design principle of TrustShield AI is that the model must
            <em> learn from the traffic it sees</em>. The system does not rely solely on
            static phishing corpora. Every email processed through either the dashboard
            or the browser extension is persisted to MongoDB, along with its
            classification result, confidence score, risk level, source and timestamp.
          </p>
          <p>
            During retraining, the system retrieves this stored email data from the
            database and uses it to update the active machine learning model. This allows
            the model to adapt to <strong>new phishing techniques and evolving attack
            patterns</strong> over time. The dataset is therefore a <em>living</em>,
            continuously growing record of real-world email behaviour.
          </p>

          <h4 className="blog-h4">Dataset schema</h4>
          <table className="blog-table">
            <thead>
              <tr>
                <th>Field</th>
                <th>Type</th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              <tr><td className="mono">email_content</td><td>String</td><td>The full text of the analyzed email.</td></tr>
              <tr><td className="mono">label</td><td>Enum</td><td>Classification: <em>phishing</em> or <em>legitimate</em>.</td></tr>
              <tr><td className="mono">confidence_score</td><td>Float [0,1]</td><td>Model probability for the predicted class.</td></tr>
              <tr><td className="mono">risk_level</td><td>Enum</td><td>Bucketed severity: low · medium · high · critical.</td></tr>
              <tr><td className="mono">source</td><td>Enum</td><td>Origin of the analysis: <em>dashboard</em> or <em>extension</em>.</td></tr>
              <tr><td className="mono">timestamp</td><td>ISODate</td><td>Time of analysis (UTC).</td></tr>
            </tbody>
          </table>
          <p className="text-sm text-muted-foreground italic">
            <strong>Table 3.</strong> Schema of the TrustShield retraining corpus stored in MongoDB.
          </p>

          <figure className="blog-figure">
            <img src={dataset} alt="Live retraining dataset preview" loading="lazy" />
            <figcaption>
              <strong>Figure 8.</strong> Snapshot of the live retraining corpus
              (<span className="mono">retrain_corpus.csv</span>) exported from MongoDB.
            </figcaption>
          </figure>

          <p>
            This continuous-learning loop ensures that the model remains <strong>adaptive,
            up-to-date and effective</strong> against contemporary phishing campaigns,
            without requiring manual curation of new training data.
          </p>
          </div>

          {/* 9. Performance */}
          <div className="section-card">
            <h2 id="sec-9" className="blog-h2">9. Performance evaluation</h2>
          <p>
            TrustShield AI was evaluated under three representative threat scenarios. The
            results below were obtained on a workstation with 16 GB RAM running a single
            Flask worker against a MongoDB instance on the same host.
          </p>
          <table className="blog-table">
            <thead>
              <tr>
                <th>Scenario</th>
                <th>Detection rate</th>
                <th>Avg. latency</th>
                <th>Notes</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="font-semibold">Standard spam</td>
                <td>≈ 98%</td>
                <td>&lt; 150 ms</td>
                <td>A cohesive filtering block formed across the corpus — almost zero leakage.</td>
              </tr>
              <tr>
                <td className="font-semibold">Spear-phishing</td>
                <td>≈ 95%</td>
                <td>&lt; 200 ms</td>
                <td>Manipulated domains and bespoke pretexts — fusion held the line.</td>
              </tr>
              <tr>
                <td className="font-semibold">Burst phishing</td>
                <td>≥ 90%</td>
                <td>&lt; 220 ms</td>
                <td>High-volume rapid-fire campaigns — the asynchronous pipeline absorbed the wave.</td>
              </tr>
            </tbody>
          </table>
          <p className="text-sm text-muted-foreground italic">
            <strong>Table 4.</strong> Detection rates and latencies measured across three threat scenarios.
          </p>
          </div>

          {/* 10. Future */}
          <div className="section-card">
            <h2 id="sec-10" className="blog-h2">10. Future work</h2>
          <p>
            Several directions are currently being explored to extend the framework:
          </p>
          <ul>
            <li><strong>Transformer-based comprehension</strong> — semantic understanding of intent rather than purely lexical features.</li>
            <li><strong>Live threat-intelligence APIs</strong> — globally sourced telemetry as a persistent additional defence layer.</li>
            <li><strong>Edge inference</strong> — execution of the model inside the extension itself, eliminating the network round-trip.</li>
            <li><strong>Autonomous remediation</strong> — automatic quarantine and sender disposal triggered before the user ever sees the message.</li>
          </ul>
          </div>

          {/* 11. See also */}
          <div className="section-card">
            <h2 id="sec-11" className="blog-h2">11. See also</h2>
          <ul>
            <li><a className="blog-link" href="#">Phishing</a></li>
            <li><a className="blog-link" href="#">Email filtering</a></li>
            <li><a className="blog-link" href="#">Machine learning</a></li>
            <li><a className="blog-link" href="#">Security information and event management (SIEM)</a></li>
            <li><a className="blog-link" href="#">Large language model</a></li>
          </ul>
          </div>

          {/* 12. References */}
          <div className="section-card">
            <h2 id="sec-12" className="blog-h2">12. References</h2>
          <ol className="text-sm">
            <li>F. P. E. Putra, A. Zulfikri, G. Arifin, and R. M. Ilhamsyah, "Analysis of phishing attack trends, impacts and prevention methods: Literature study," <em>Brilliance: Research of Artificial Intelligence</em>, vol. 4, no. 1, pp. 413–421, 2024.</li>
            <li>M. Alghenaim, G. Alkawsi, and C. R. Barnhart, "The state of the art in ai-based phishing detection: A systematic literature review," <em>Studies in Computational Intelligence</em>, vol. 1178, 2025.</li>
            <li>K. Afane, W. Wei, Y. Mao, J. Farooq, and J. Chen, "Next-generation phishing: How llm agents empower cyber attackers," <em>IEEE International Conference on Big Data (BigData)</em>, pp. 2558–2567, 2024.</li>
            <li>S. S. Roy, P. Thota, K. V. Naragam, and S. Nilizadeh, "From chatbots to phishbots?: Phishing scam generation in commercial large language models," <em>IEEE Symposium on Security and Privacy (SP)</em>, pp. 36–54, 2024.</li>
            <li>P. H. Kyaw, J. Gutierrez, and A. Ghobakhlou, "A systematic review of deep learning techniques for phishing email detection," <em>Electronics</em>, vol. 13, no. 3823, Sep 2024.</li>
            <li>Pedregosa, F. et al. <em>Scikit-learn: Machine Learning in Python.</em> JMLR 12, 2011.</li>
            <li>Google. <em>Chrome Extensions: Manifest V3 documentation.</em> 2024.</li>
            <li>Ollama Project. <em>phi model card.</em> 2024.</li>
          </ol>
          </div>

          <div className="mt-10 pt-4 border-t border-border text-xs text-muted-foreground">
            This blog was last edited on 26 April 2026, by <a href="#" className="blog-link">TrustShield AI Team</a>.
            Text is available under the open documentation license; the source code is
            published on{" "}
            <a href="https://github.com/Tejus468/pfsd_project" className="blog-link">
              github.com/Tejus468/pfsd_project
            </a>.
          </div>
        </article>
      </main>

      <footer className="border-t border-border bg-secondary/40 mt-12 py-6">
        <div className="container mx-auto max-w-[1100px] flex flex-col md:flex-row items-center justify-between gap-3 text-xs text-muted-foreground">
          <div>TrustShield Blog · 2026</div>
          <div>Written by TrustShield AI Team · Issue 04</div>
        </div>
      </footer>
    </div>
  );
};

export default Index;
